// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/Drawers.tsx";
import * as $$1 from "./islands/MenuButton.tsx";
import * as $$2 from "./islands/Newsletter.tsx";
import * as $$3 from "./islands/SliderJS.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/Drawers.tsx": $$0,
    "./islands/MenuButton.tsx": $$1,
    "./islands/Newsletter.tsx": $$2,
    "./islands/SliderJS.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
